name: discore_ghpages
description: Discore github pages site.
version: 0.1.0

dependencies:
  angular2: ^3.0.0
  markdown: 0.11.3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
